### ISSUE TITLE
JIRA mobile view

### ISSUE THREAD

**Issue by seanherron** [Fuchs/jira-remote-user-sso#1]
Hello,

I'm using this to great success on JIRA (thank you!). One thing I've noticed - when `X-Forwarded-User` is presented while the user is on a mobile device (so the JIRA mobile view is active), the plugin does not log the user in. Is there a way to enable this?

Thank you.

**Comment by Fuchs** [comment]
Hi seanherron, glad to hear that you can use the plugin. 
I'm afraid that we so far never used the JIRA mobile view, thus I have no idea. I assume it should be possible, though. Maybe you can figure it out (pull requests welcome), if not I see if I can have a look at it. Might take a while though, as we are currently busy with other projects. 
This is also the reason for the late reply, sorry for that :(

Thanks for the report and kind regards, 

Christian
