### ISSUE TITLE
Exception when retrieving user from session

### ISSUE THREAD

**Issue by skisoccer13** [Fuchs/jira-remote-user-sso#3]
Though this does seem to work as it is intended, the atlassian-jira-security.log files are being spammed with messages like:

getUserFromSession : Exception when retrieving user from session: java.lang.ClassCastException: java.lang.String cannot be cast to java.security.Principal

It originates from BielBienneAuthenticator.getUser(String username)

**Comment by Fuchs** [comment]
Thanks for the report, I see that we can get this fixed, it's possible that the signature changed, what version are you compiling it against?

**Comment by skisoccer13** [comment]
We are compiling against 6.2.6 but running JIRA 6.4.x

**Comment by Fuchs** [comment]
Right, thank you very much for the report, I'll see that someone can have a look at it when we have the time. 
Thanks for the patience, I hope it's not filling up your logs too much.
