### ISSUE TITLE
Modifications on seraph-config.xml

### ISSUE THREAD

**Issue by jpfelgueiras** [Fuchs/jira-remote-user-sso#4]
Could you please explain the modifications of the file seraph-config.xml on a wiki page? 

Thank you for your good work.

**Comment by Fuchs** [comment]
Hi, it seems like this dropped out of the README somehow, I'll see if I find an old config file of mine and re-add it, thanks for the report. As stated: I'm afraid I can't maintain the 4 Atlassian SSO plugins any longer, at least for now. But this should be possible.

**Comment by Fuchs** [comment]
There, this should do it. Do comment out any other authenticator lines and add the one from the README.md instead in the config file mentioned.

**Comment by jpfelgueiras** [comment]
Thank you for your help. 

I will try to modify the plugin to use version 2. If it works I will make a pull request.
